### PR TITLE
Updates from GoOrchids

### PR DESCRIPTION
**Pull request by alecpm**
Changes merged:

* Better sorting of character values returned by api
* Inflect plurals of glossary terms
* Handle empty image url in glossary API
* Don't implicitly filter out capitalized glossary entries.  Ensure glossary blob info is looked up case-insensitively.
* Add natural keys for all frequently referenced models to allow for clean fixture import/export.
* Remove any null/null lengths in CV editor, rather than explicitly setting them.
* Make plantshare dependency in search optional
* Load image_types select even if there's a hash that doesn't specify image_type
* Toggle icon on questions header
* Fix management of 'active' class on filter divs
* Updated PyPI version pins (django-tinymce, django-facebook-connect, django-piston)
* Be more tolerant of different memcachier server separator tokens.

### CODE REVIEW

**Comment by jnga** [comment]
Thanks very much. We should be able to get these in within the next couple of weeks, after the Django updates are deployed and merged.

**Comment by jnga** [comment]
The following changes from this pull request have been merged to master:

- Be more tolerant of different memcachier server separator tokens.
- Pin django-tinymce, since 2.2.0 is broken.
- Don't implicitly filter out capitalized glossary entries. Ensure glos… …
- handle empty image url
- Add optional rank import based on filename
- try a way of inflecting plurals of glossary terms
- Groups List Page is optional
- Only populate 3rd level page history entry if browser hash has a _fil… …
- Remove any null/null lengths, rather than explicitly setting them.
- Remove circular dependencies in natural key setup.
- Add natural keys for all frequently referenced models to allow for cl… …
- Make the lit source fields expand on focus for ease of text entry.
- Add natural key import/export to pertnersite model
- Revert "Revert "check the right permission name"" …

This was done after our Django upgrades were merged. So, these changes are all in master that now runs on Django 1.8.

Several changes were not merged, either because they were already in the codebase, they seemed specific to Go Orchids, or they could use some clarification or testing. Please feel free to open separate issues or pull requests as needed and we will look into them as soon as we can.

**Comment by alecpm** [comment]
Thanks John!  I'll go through and see if there's anything that might be important missing and make separate pull requests for those.

**Comment by jnga** [comment]
You're welcome, Alec, and thanks.

One of the items above, addressed by commit c421c54, was something we had run into too and fixed via CSS (with display: block or inline-block).

**Pull request closed without merging**
